# Generated by Django 5.2.5 on 2025-09-26 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Account No')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Phone')),
                ('expenditure', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Expenditure (Ksh)')),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Account Balance (Ksh)')),
                ('joined', models.DateTimeField(auto_now_add=True, verbose_name='Joined')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='System User')),
            ],
            options={
                'verbose_name': 'Hotspot Customer',
                'verbose_name_plural': 'Hotspot Customers',
            },
        ),
    ]
