# Generated by Django 5.2 on 2025-09-26 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_api', '0002_hotspotcustomer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100, unique=True, verbose_name='Plan Name')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Unlimited')),
                ('data_limit_mb', models.IntegerField(default=0, help_text='Data limit in MB (0 for unlimited)')),
                ('speed_limit', models.CharField(default='3M/3M', max_length=20, verbose_name='Upload/Download Speed')),
                ('validity_minutes', models.IntegerField(default=60, help_text='Time validity in minutes (e.g., 60 for 1hr, 1440 for 24hrs)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (Ksh)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hotspot Plan',
                'verbose_name_plural': 'Hotspot Plans',
                'ordering': ['price', 'validity_minutes'],
            },
        ),
        migrations.AlterModelOptions(
            name='hotspotcustomer',
            options={},
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='data_limit_mb',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='time_limit_minutes',
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='ssid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='account_no',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='expenditure',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='merchant_request_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='access_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotspot_api.accesspoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='login_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(editable=False, max_length=12, ),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='plan_name',
            field=models.CharField(max_length=100),
        ),
    ]
