# Generated by Django 5.2.5 on 2025-09-28 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_api', '0003_hotspotplan_alter_hotspotcustomer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesspoint',
            options={
                'ordering': ['name'],
                'verbose_name': 'Access Point',
                'verbose_name_plural': 'Access Points'
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={
                'ordering': ['-last_seen'],
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices'
            },
        ),
        migrations.AlterModelOptions(
            name='hotspotcustomer',
            options={
                'ordering': ['-joined'],
                'verbose_name': 'Hotspot Customer',
                'verbose_name_plural': 'Hotspot Customers'
            },
        ),
        migrations.AlterModelOptions(
            name='mpesatransaction',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions'
            },
        ),
        migrations.AlterModelOptions(
            name='usagedata',
            options={
                'ordering': ['-login_time'],
                'verbose_name': 'Usage Session',
                'verbose_name_plural': 'Usage Sessions'
            },
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers'
            },
        ),

        # Remove old field
        migrations.RemoveField(
            model_name='usagedata',
            name='data_used_gb',
        ),

        # AccessPoint new fields
        migrations.AddField(
            model_name='accesspoint',
            name='current_clients',
            field=models.IntegerField(default=0, verbose_name='Current Clients'),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='last_reboot',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Reboot'),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='max_clients',
            field=models.IntegerField(default=50, verbose_name='Maximum Clients'),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='total_data_gb',
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name='Total Data Usage (GB)'
            ),
        ),

        # Device new fields
        migrations.AddField(
            model_name='device',
            name='customer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='hotspot_api.hotspotcustomer',
                verbose_name='Customer'
            ),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(
                choices=[
                    ('PHONE', 'Mobile Phone'),
                    ('LAPTOP', 'Laptop'),
                    ('TABLET', 'Tablet'),
                    ('DESKTOP', 'Desktop Computer'),
                    ('OTHER', 'Other Device')
                ],
                default='OTHER',
                max_length=10,
                verbose_name='Device Type'
            ),
        ),
        migrations.AddField(
            model_name='device',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, verbose_name='First Seen'),
        ),
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Currently Online'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Seen'),
        ),
        migrations.AddField(
            model_name='device',
            name='total_data_mb',
            field=models.IntegerField(default=0, verbose_name='Total Data Usage (MB)'),
        ),
        migrations.AddField(
            model_name='device',
            name='total_sessions',
            field=models.IntegerField(default=0, verbose_name='Total Sessions'),
        ),

        # HotspotCustomer new fields
        migrations.AddField(
            model_name='hotspotcustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='hotspotcustomer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='hotspotcustomer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),

        # M-Pesa Transaction new fields
        migrations.AddField(
            model_name='mpesatransaction',
            name='account_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Account Reference'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='M-Pesa Receipt'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='transaction_desc',
            field=models.CharField(blank=True, max_length=200, verbose_name='Transaction Description'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='voucher',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='hotspot_api.voucher',
                verbose_name='Generated Voucher'
            ),
        ),

        # UsageData new fields
        migrations.AddField(
            model_name='usagedata',
            name='customer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='hotspot_api.hotspotcustomer',
                verbose_name='Customer'
            ),
        ),
        migrations.AddField(
            model_name='usagedata',
            name='data_used_mb',
            field=models.IntegerField(default=0, verbose_name='Data Used (MB)'),
        ),
        migrations.AddField(
            model_name='usagedata',
            name='device',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='hotspot_api.device',
                verbose_name='Device'
            ),
        ),
        migrations.AddField(
            model_name='usagedata',
            name='download_speed_mbps',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name='Download Speed (Mbps)'
            ),
        ),
        migrations.AddField(
            model_name='usagedata',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='usagedata',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, verbose_name='MAC Address'),
        ),
        migrations.AddField(
            model_name='usagedata',
            name='session_duration_minutes',
            field=models.IntegerField(default=0, verbose_name='Session Duration (Minutes)'),
        ),
        migrations.AddField(
            model_name='usagedata',
            name='signal_strength',
            field=models.IntegerField(
                blank=True,
                help_text='Signal strength in dBm',
                null=True,
                verbose_name='Signal Strength'
            ),
        ),
        migrations.AddField(
            model_name='usagedata',
            name='upload_speed_mbps',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name='Upload Speed (Mbps)'
            ),
        ),
        migrations.AddField(
            model_name='usagedata',
            name='voucher',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='hotspot_api.voucher',
                verbose_name='Voucher Used'
            ),
        ),

        # Voucher new fields
        migrations.AddField(
            model_name='voucher',
            name='created_by_transaction',
            field=models.CharField(
                blank=True,
                help_text='Checkout request ID that created this voucher',
                max_length=100
            ),
        ),
        migrations.AddField(
            model_name='voucher',
            name='data_limit_mb',
            field=models.IntegerField(
                blank=True,
                help_text='Data limit in MB, null for unlimited',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='voucher',
            name='data_used_mb',
            field=models.IntegerField(default=0, help_text='Data used in MB'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires On'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Activity'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Customer Phone'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Used At'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='used_by_device',
            field=models.CharField(
                blank=True,
                help_text='MAC address of device that used this voucher',
                max_length=17
            ),
        ),

        # Alter existing fields
        migrations.AlterField(
            model_name='accesspoint',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Firmware Version'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='installation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Installation Date'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Online Status'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='mac_address',
            field=models.CharField(max_length=17, unique=True, verbose_name='MAC Address'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Access Point Name'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='ssid',
            field=models.CharField(max_length=50, verbose_name='SSID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=100, verbose_name='Device Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=17, unique=True, verbose_name='MAC Address'),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Account Balance'),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='account_no',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='expenditure',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Expenditure'),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Checkout Request ID'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Merchant Request ID'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('COMPLETED', 'Completed'),
                    ('FAILED', 'Failed'),
                    ('CANCELLED', 'Cancelled')
                ],
                default='PENDING',
                max_length=20,
                verbose_name='Status'
            ),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_id',
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name='Transaction ID'
            ),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='access_point',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='hotspot_api.accesspoint',
                verbose_name='Access Point'
            ),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='login_time',
            field=models.DateTimeField(verbose_name='Login Time'),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Logout Time'),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(editable=False, max_length=12, unique=True, verbose_name='Voucher Code'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='plan_name',
            field=models.CharField(max_length=100, verbose_name='Plan Name'),
        ),
    ]
