# Generated by Django 5.2.5 on 2025-09-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_api', '0004_alter_accesspoint_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='current_clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='installation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='last_reboot',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='mac_address',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='max_clients',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='ssid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='total_data_gb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotspot_api.hotspotcustomer'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('PHONE', 'Mobile Phone'), ('LAPTOP', 'Laptop'), ('TABLET', 'Tablet'), ('DESKTOP', 'Desktop Computer'), ('OTHER', 'Other Device')], default='OTHER', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='total_data_mb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='total_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='account_no',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='expenditure',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotspotcustomer',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='hotspotplan',
            name='validity_minutes',
            field=models.IntegerField(default=60, help_text='Time validity in minutes'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='account_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotspot_api.voucher'),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='access_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotspot_api.accesspoint'),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotspot_api.hotspotcustomer'),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='data_used_mb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotspot_api.device'),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='download_speed_mbps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='login_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='session_duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='signal_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='upload_speed_mbps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='usagedata',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotspot_api.voucher'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created_by_transaction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='data_limit_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='data_used_mb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='used_by_device',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
