# Generated by Django 5.2 on 2025-10-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_api', '0005_otp_alter_accesspoint_current_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='customer_credited',
            field=models.BooleanField(default=False, help_text='True if customer expenditure has been updated.'),
        ),
    ]
