# Generated by Django 5.2.5 on 2025-10-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_api', '0006_mpesatransaction_customer_credited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.AddField(
            model_name='voucher',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC Address'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='validity_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Validity (Hours)'),
        ),
    ]
