# Generated by Django 5.2.5 on 2026-03-18 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_api', '0007_alter_otp_options_voucher_mac_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('total_points', models.IntegerField(default=0, help_text='Current available points')),
                ('lifetime_earned', models.IntegerField(default=0, help_text='All-time points earned')),
                ('lifetime_redeemed', models.IntegerField(default=0, help_text='All-time points redeemed')),
                ('total_spent_ksh', models.DecimalField(decimal_places=2, default=0, help_text='Cumulative Ksh spent (used to compute points)', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Points',
                'verbose_name_plural': 'Customer Points',
                'ordering': ['-total_points'],
            },
        ),
        migrations.AlterField(
            model_name='hotspotplan',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotspotplan',
            name='plan_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hotspotplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotspotplan',
            name='speed_limit',
            field=models.CharField(default='3M/3M', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotspotplan',
            name='validity_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='customer_credited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='plan_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='validity_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='KopaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('amount_ksh', models.DecimalField(decimal_places=2, help_text='Principal borrow amount in Ksh', max_digits=8)),
                ('fee_ksh', models.DecimalField(decimal_places=2, help_text='Convenience fee in Ksh', max_digits=8)),
                ('data_mb', models.IntegerField(help_text='Data granted in MB')),
                ('status', models.CharField(choices=[('PENDING', 'Pending OTP'), ('ACTIVE', 'Active'), ('REPAID', 'Repaid'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('repaid_at', models.DateTimeField(blank=True, null=True)),
                ('repaid_via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kopa_repayment', to='hotspot_api.mpesatransaction')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kopa_voucher', to='hotspot_api.voucher')),
            ],
            options={
                'verbose_name': 'Kopa Transaction',
                'verbose_name_plural': 'Kopa Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('points', models.IntegerField(help_text='Positive = earned, Negative = redeemed')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Earned'), ('REDEEM', 'Redeemed'), ('ADJUST', 'Admin Adjustment')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mpesa_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotspot_api.mpesatransaction')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotspot_api.voucher')),
            ],
            options={
                'verbose_name': 'Points Transaction',
                'verbose_name_plural': 'Points Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
